<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-OP77TC5A" name="Personal Loan" tests="4" failures="1" timestamp="17 May 2020 07:31:35 GMT" time="0.092" errors="0">
  <testcase name="Demo" time="0.005" classname="test.first.Test1"/>
  <testcase name="DemoTwoPersonalLoan" time="0.006" classname="test.first.Test2"/>
  <testcase name="ploan" time="0.002" classname="test.first.Test2"/>
  <testcase name="SecondTest" time="0.009" classname="test.first.Test1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.first.Test1.SecondTest(Test1.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
